blocto/sdk-toolkit

package.json, src/components/AptosEditor.tsx, src/components/Editor.tsx, src/scripts/aptos/Modules.ts, src/scripts/aptos/Resource.ts, src/scripts/aptos/SignMessage.ts, src/types/ScriptTypes.ts, yarn.lock
=> [Feature] Add sign message on Aptos

src/context/Context.tsx, src/scripts/solana/Contract.ts, yarn.lock
- solana get contract uint8Array
=> [Fix] solana getContract response unit8Array

.github/pr-labeler.yml, .github/pull_request_template.md, .github/workflows/pr-labeler.yml
- add pr template and pr labeler action setting.
- ref: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository
=> [Enhance] Add pr template and pr labeler setting

.github/workflows/create-asana-attachment.yaml
- I've add a github bot to frontend-internal project in Asana, then set a secret in Github settings.
- And an corresponding github action also need to be settled. ref [here](https://github.com/Asana/create-app-attachment-github-action).
- set a white list for frontend-internal with this action ( projectId: `1201812548509877`) 
**Asana**: https://app.asana.com/0/1201812548509877/1203407537075202/f
**Mockup**: -   
- https://github.com/Asana/create-app-attachment-github-action
-
=> Add asana-git intergration. 

src/components/Editor.tsx, src/scripts/aptos/Resource.ts, src/types/ScriptTypes.ts, src/utils/hexToBytes.ts
**Asana**:   https://app.asana.com/0/1201812548509877/1203881426977707/f
**Mockup**:
=> [Feature]  args type add bytes type

package.json, yarn.lock
=> [Enhance] Upgrade blocto sdk to 0.4.0-beta.5

src/components/LoginModal.tsx, src/context/Context.tsx, src/index.tsx, src/utils/verifyAccountProofSignature.ts
Support the new version of account proof service, which should generate the signature with `appIdentifier` and `nonce`
=> [Feature] Update to the new version of account prrof service

package.json, yarn.lock
Upgrade Blocto SDK to fix Aptos signing message
**Asana**:  https://app.asana.com/0/0/1204029950756246/f
**Mockup**:
=> [Enhance] Upgrdae Blocto SDK version

package.json, yarn.lock
**Asana**:  
**Mockup**:  
https://github.com/facebook/create-react-app/issues/11773
=> [Fix] hot reload

package.json, src/components/EvmEditor.tsx, src/contracts/arbitrum.ts, src/contracts/index.ts, src/contracts/optimism.ts, src/services/arbitrum.ts, src/services/index.ts, src/services/optimism.ts, src/services/rinkeby.ts, src/types/ChainTypes.ts, yarn.lock
- add chain info of  arbitrum and optimism.
**Asana**:  
**Mockup**:  
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1204200709519569
- https://app.asana.com/0/0/1204343719537803
=> Feat: add l2 chain info

package.json, src/components/EvmEditor.tsx, src/contracts/goerli.ts, src/contracts/index.ts, src/services/arbitrum.ts, src/services/bscTestnet.ts, src/services/fuji.ts, src/services/goerli.ts, src/services/index.ts, src/services/mumbai.ts, src/services/optimism.ts, yarn.lock
- deploy a testing contract on Goerli.
- change setting in sdk-toolkit for goerli.
- contract : https://goerli.etherscan.io/address/0xfb9688306d687f16c6d658fa2a04e0fb59071212
**Asana**:  https://app.asana.com/0/1201812548509877/1204512243266975/f
**Mockup**:
=> Add settings for supporting goerli

package.json, src/components/AptosEditor.tsx, src/types/ScriptTypes.ts, yarn.lock
I fix the wrong type in sdk, but here is wrong too.
**Asana**:  
**Mockup**:
=> Fix: aptos editor types

src/services/solanaDevnet.ts
=> fix: update solana mainnet rpc url

package.json, src/components/AptosEditor.tsx, src/components/Editor.tsx, src/components/EvmEditor.tsx, src/components/FlowEditor.tsx, src/components/SolanaEditor.tsx, src/contracts/arbitrum.ts, src/contracts/bsc.ts, src/contracts/fuji.ts, src/contracts/mumbai.ts, src/contracts/optimism.ts, src/scripts/evm/Transactions.ts, src/scripts/evm/UserOperations.ts, src/types/ScriptTypes.ts, yarn.lock
- and update the evm dev contract abi/address.
- add 3 situation with call data : 
Transfer native token
```
b61d27f600000000000000000000000050504ab483c9bde3af9700b5fe77a860d81b3e4f00000000000000000000000000000000000000000000000000038d7ea4c6800000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000000
```
toolkit contract setValue = 1
```
b61d27f6000000000000000000000000dc5fd9220511a7211719dd8206ec2d686054bcc00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000245524107700000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000 …
```
=> Support sendUserOperation for QA to test to feature.

package.json, src/components/Editor.tsx, src/components/EvmEditor.tsx, yarn.lock
- fix callback handling
- upgrade blocto sdk
**Asana**:  
**Mockup**:
=> fix: callback for sending tx/user-operation

package.json, yarn.lock
fix disconnect and switch account issue
**Asana**:  
**Mockup**:
=> feat: upgrade blocto sdk to 0.5.0-beta.8

src/scripts/aptos/Modules.ts, src/scripts/aptos/Script.ts, src/scripts/evm/Transactions.ts, src/scripts/flow/Transactions.ts, src/scripts/solana/Transactions.ts
- fix recipient typo
**Slack**:  https://portto.slack.com/archives/CPW507126/p1687935498787129
=> fix: fix recipient typo

package.json, yarn.lock
upgrade blocto sdk to 0.5.0-beta.9
**Asana**:  
**Mockup**:
=> Feat: update-sdk-beta.9

package.json, yarn.lock
Update blocto sdk to 0.5.0-beta.13
**Asana**:  
**Mockup**:
=> Chore: update blocto sdk 0.5.0-beta13

package.json, yarn.lock
Update blocto sdk to `0.5.0-beta.14`
**Asana**:  
**Mockup**:
=> Chore: update-sdk

package.json, yarn.lock
=> feat: update blocto sdk to 0.5.0

package.json, src/components/EvmEditor.tsx, yarn.lock
- update sdk to 0.6.0-beta to support switch chain ui
**Asana**:  
**Mockup**:
=> chore: update sdk to 0.6.0-beta

src/components/AptosEditor.tsx, src/contracts/index.ts, src/scripts/aptos/ModuleArgs.ts, src/scripts/aptos/Modules.ts, src/scripts/aptos/Script.ts, src/types/ScriptTypes.ts
- Add test cases for Aptos
**Asana**:  
- https://app.asana.com/0/1201812548509877/1205230001798529/f
- https://app.asana.com/0/1201812548509877/1203462425242084/f
**Mockup**:
=> feat: add test cases for Aptos

package.json, yarn.lock
- update blocto sdk to 0.6.0 beta.7
**Asana**:  
**Mockup**:
=> Chore/update sdk 0.6.0 beta.7

package.json, yarn.lock
update blocto sdk to 0.7.0-beta.1
**Asana**:  
**Mockup**:
=> chore: update blocto sdk to 0.7.0-beta.1

src/services/evm.ts
https://app.asana.com/0/1201812548509877/1205343582608233/f
=> fix: fix optimism chain id hex format

package.json
`@blocto/sdk` update to 0.7.1-beta.0
**Asana**:  
**Mockup**:
=> chore: update sdk to 0.7.1-beta.0

src/components/EvmEditors/EvmSendEditor.tsx, yarn.lock
as title
**Asana**:  
**Mockup**:
=> fix: yarn install update lock file

package.json, yarn.lock
- update @blocto/sdk 0.7.2 
**Asana**:  
**Mockup**:
=> feat: update sdk version

package.json, yarn.lock
update `@blocto/sdk` dependency for QA testing disable `eth_sgin` feature
**Asana**:  
**Mockup**:
=> feat: update sdk to 0.8.1-beta.0

package.json, yarn.lock
Update fcl to 1.4.0
**Asana**:  
**Mockup**:
=> build: update fcl version

package.json, yarn.lock
=> feat: update sdk beta version

src/components/EvmEditor.tsx, src/components/EvmEditors/EvmSignEditor.tsx, src/utils/isValidSignature.ts
remove eth_sign feature
**Asana**:  https://app.asana.com/0/1201812548509877/1205568012433449/f
**Mockup**:
=> feat: remove eth_sign feature

src/components/EvmEditors/EvmRequestEditor.tsx
receive JSON string as params
**Asana**:  https://app.asana.com/0/1201812548509877/1205880493576958/f
**Mockup**:
=> enhance: receive objects as params

src/components/EvmChainSelect.tsx
Fix "useEffect" is defined but never used warning
**Asana**:  
**Mockup**:
=> fix: build warning

src/components/EvmEditors/EvmBatchTxEditor.tsx
=> fix: send batch transactions

src/components/EvmEditors/EvmBatchTxEditor.tsx, src/contracts/abi/ERC721.json
=> feat: batch template add mintNFT (scroll testnet)

Dockerfile.dev
support with [wallet-web-docker](https://github.com/blocto/wallet-web-docker) 
**Asana**:  
**Mockup**:
=> feat: add dockerfile

package.json, src/services/evm.ts, yarn.lock
add L2 blast mainnet & testnet
**Asana**:  
- https://app.asana.com/0/1201812548509877/1206533596895345/f
- https://app.asana.com/0/1201812548509877/1206724420219402/f
**Mockup**:
=> feat: add l2 blast

package.json
update the blocto sdk to test the SDK passing URL parameters feature
**Asana**:  
**Mockup**:
=> build: update blocto sdk

.github/workflows/create-asana-attachment.yaml
update asana project id for attaching PRs' links
**Asana**:  
**Mockup**:
=> chore: update asana project id

package.json, src/services/evm.ts, yarn.lock
**Asana**:  https://app.asana.com/0/0/1207291884217733/f
**Mockup**:
=> feat: support merlin chain
